### ISSUE TITLE
[Feedback - N.A.I.]

### ISSUE THREAD

**Issue by ghost** [FaceDeer/magma_conduits#1]
"Not An Issue"; they should allow some form of messaging for feedback and similar.

I've tried this mod in a flat mapgen map, it looks impressive.
The hot stone looks great, I would use it instead of obsidian because it immediately makes you think "there's something HOT behind this".
I also like very much how it surrounds lava when it starts to flow on some flat surface, i.e. non vertical caves.

A mountain + a magma conduit in it = volcano. It would be awesome.
I know that there's a volcano mod, which creates them.
But I think that this is better because it adds beauty to the minetest mountains, which are already impressive.

It seems that soon I'll have to add yet another mod to my game... *sigh* :)

**Comment by FaceDeer** [comment]
I've been pondering how to make this mod interact with the surface world better, actual volcanoes would be ideal. Came across [an issue in minetest itself](https://github.com/minetest/minetest/issues/7364) in the process of experimenting with that, though.

I think I'll probably need to switch away from using "vein" ore to make the magma conduits at some point soon, and use some variation of the code that currently makes the giant stalactites in subterrane. That will allow me to know where the magma vein intersects with the surface, which will let me generate large structures around it.

**Comment by FaceDeer** [comment]
Finally merged the volcano branch, volcanoes are now a thing. :)
